name: Tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-20.04
        - macos-latest
        - windows-latest
        python-version:
        - '2.7'
        - '3.5'
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - pypy-2.7
        - pypy-3.8
        - pypy-3.9
        extras:
        - none
        - scipy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build tools
      run: python -m pip install tox-gh-actions wheel
    - name: Install optional dependencies (extras)
      run: conda install -c anaconda ${{ matrix.extras }}
      if: ${{ matrix.extras != 'none' }}
    - name: Run tests
      run: tox
